name: Build & Deploy React App to ECR

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: react-client

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Get short commit SHA
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      run: |
        docker build -t $ECR_REPO:${{ steps.vars.outputs.SHORT_SHA }} .
        docker push $ECR_REPO:${{ steps.vars.outputs.SHORT_SHA }}

    - name: Update image tag in Kubernetes manifest
      run: |
        sed -i "s|image: .*$|image: $ECR_REPO:${{ steps.vars.outputs.SHORT_SHA }}|" k8s/manifests/frontend.yaml

    - name: Commit and push manifest change
      run: |
        git config user.name "github-actions"
        git config user.email "gha@github.com"
        git add k8s/manifests/frontend.yaml
        git commit -m "Update image tag to ${{ steps.vars.outputs.SHORT_SHA }}"
        git push
